# Generated by Django 3.2.8 on 2021-10-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardbilllist',
            old_name='id_number',
            new_name='bill_id',
        ),
    ]
